### PR TITLE
Properly process capitalized commands

### PR DESCRIPTION
**Pull request by perilstar**
I think this is pretty self-explanatory...

### CODE REVIEW

**Comment by Kodehawa** [comment]
Believe me, that won't work properly on production. Yes I tried. Yes I know it makes no sense.


Fixed on 5.0 though.

**Comment by queer** [comment]
Mantaro devs LITERALLY don't know how to code!!! Click [HERE](https://mantaro.site/) to learn more!!!1

**Comment by perilstar** [comment]
In that case, you just call `.toLowerCase()` in the `register()` and related methods, as well..

**Comment by Kodehawa** [comment]
people can have custom commands with upper and lower case in whatever way they want, why would I need to lowercase those

**Comment by perilstar** [comment]
@Kodehawa consistency

**Comment by perilstar** [comment]
If you lowercase all the keys in the registry, then the custom commands can be called with ANY capitalisation.

**Comment by Kodehawa** [comment]
in 5.0 custom command registry and normal command registry are different so this is a non-issue

**Comment by Kodehawa** [comment]
people really want commands with *really* specific capitalization sometimes


i almost got pitchforked last time i tried to do that

**Pull request closed without merging**
