### PR TITLE
Redis cache 

### PR DESCRIPTION
**Pull request by Kodehawa**
Incomplete, for now fails on getting Player objects properly.

### CODE REVIEW

**Comment by Kodehawa** [comment]
Complete :tm:

Should be good for production soon enough I'd guess.

**Comment by natanbc** [comment]
First some testing on mantaro patreon, then if nothing implodes after a decent time we move to the main bot

**Comment by Kodehawa** [comment]
That's how it goes basically for db changes

**Comment by Kodehawa** [comment]
I wonder how many times commits are repeated because rebase made memes

**Comment by Kodehawa** [comment]
This should get merged after #87

**Comment by Kodehawa** [comment]
Complete.

**Pull request merged**
