### PR TITLE
Allow others to pet someone's pet.

### PR DESCRIPTION
**Pull request by netux**
Makes `~>pet pet` accept an user argument to pet that player's pet.

Adds alternative error strings for petting other player's pets to the en_US locale, and changes pet reactions to mention the pet's name instead of addressing the owner as "you".

### CODE REVIEW

**Comment by Kodehawa** [comment]
lgtm, but could you indent it with 4 spaces instead of a tab? that's mostly because GH messes up mixed indents and we use 4 spaces :P

I really should add a code style contrib guideline somewhere

I'll merge it afterwards

**Comment by netux** [comment]
Everywhere I check the indentation seems to use 4 spaces: selected the text to make sure, forced my IDE to reindent the lines with 4 spaces, even disabled the stylesheet I have which makes GitHub render tabs as 2 spaces.

Am I missing something? 🤨

**Comment by Kodehawa** [comment]
image

I mean...

Try re-indenting those? I checked and I use 4 spaces on my IDE 🤔

**Comment by Kodehawa** [comment]
Ah yeah it's fine. It was just the change thingy on GH rendering it wrongly :)

If it's ready to merge, I'll do so in a few. Thanks!

**Comment by Kodehawa** [comment]
🚀

**Pull request merged**
