### PR TITLE
lt_LT.json | More strings soonTM

### PR DESCRIPTION
**Pull request by TheOnlyGhostwolf**

### CODE REVIEW

**Comment by Kodehawa** [comment]
idgi, this is impossible to merge and idgi how should i resolve conflicts, lol.

**Comment by Kodehawa** [comment]
(it shows "two conflicts" as it being the whole file)

**Comment by MrLar** [comment]
Thats because indentation changed too much

**Comment by Kodehawa** [comment]
L.

**Comment by MrLar** [comment]
You can technically revolve it my just accepting incoming

**Comment by Kodehawa** [comment]
how to open again 101

**Comment by MrLar** [comment]
You just did

**Comment by Kodehawa** [comment]
added manually

**Pull request closed without merging**
