### PR TITLE
Make Mantaro webscale. Also adds ~>webscale

### PR DESCRIPTION
**Pull request by queer**

### CODE REVIEW

**Comment by Kodehawa** [comment]
amy plz

**Comment by queer** [comment]
Is clearly vvv. important pr, plz merge asap

**Comment by Kodehawa** [comment]
I'm dying, you all memes

**Comment by MrLar** [comment]
Mantaro only has Professional Devs

**Comment by Kodehawa** [comment]
I've been laughing for 5 minutes straight, help

**Comment by MrLar** [comment]
There is no more help.

**Comment by Kodehawa** [comment]
:(

**Pull request merged**
