### PR TITLE
Added redis caching

### PR DESCRIPTION
**Pull request by natanbc**

### CODE REVIEW

**Comment by Kodehawa** [comment]
As a reminder, before merging this needs extensive testing, maybe on the beta branch of the public bot after everything is deemed to work on testing?

**Comment by Kodehawa** [comment]
Premium keys (#52) have been merged into this branch since this was used as a base and they're working properly.

**Comment by Kodehawa** [comment]
omg rebasing and reworking this from development made like a zillion commits appear here lol

**Comment by Kodehawa** [comment]
avarel pls

**Comment by natanbc** [comment]
smh

**Comment by Kodehawa** [comment]
Closed because it needs significant changes to continue and it's unmergeable for now.

**Comment by natanbc** [comment]
pat

**Pull request closed without merging**
