### PR TITLE
Update Russian language

### PR DESCRIPTION
**Pull request by Alex18life**
There are a lot of errors in this translation, we need to fix it, I made some changes, but the question is: How does Mantaro address the user? You or you?

### CODE REVIEW

**Comment by MrLar** [comment]
I am 99% sure we do not take translation contributions outside of our [Crowdin project](https://crowdin.com/project/mantarobot) (will leave this open and let Kode decide though). As for your question it somewhat courtesy for Mantaro to address the user formally on stuff that is more serious (as in opts, waifu optout etc.) but generally speaking the user is just addressed casually and in whatever way your language allows to express that.

**Comment by Alex18life** [comment]
Understood about the address. About the translation correction: it is better to discuss with Kodehawa itself?

**Comment by Alex18life** [comment]
Wait. Where do you translate Mantaro commands? Into Crowdin or Github?

**Comment by Kodehawa** [comment]
Crowdin.

**Comment by Alex18life** [comment]
A... Okay.

**Review by luka32-jpn — APPROVED** [review]

**Review by luka32-jpn — APPROVED** [review]

**Pull request closed without merging**
